name: ci

on:
  push:
    branches:
      - 'x'
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      -
        name: Clone repository
        run: |
          sudo apt update
          sudo apt install git -y
          git clone https://${{ secrets.GH_TOKEN }}@github.com/${{ secrets.GH_REPO }} ult
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ult
          push: true
          tags: ghcr.io/hell-pokemon/special-octo-waddle:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
